coins = {
    "AXE":{
        "min_swap": 1,
        "api-id": "axe",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": [{"url":"electrum1.cipig.net:10057"},
                     {"url":"electrum2.cipig.net:10057"},
                     {"url":"electrum3.cipig.net:10057"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "BAT":{
        "min_swap": 0.5,
        "activate_with":"electrum",
        "api-id": "basic-attention-token",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "reserve_balance":500,
        "premium":1.03,
        "min_swap":1,
        "minQty":"1.00000000",
        "maxQty":"90000000.00000000",
        "stepSize":"1.00000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "AWC":{
        "min_swap": 0.5,
        "activate_with":"electrum",
        "api-id": "",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": True,
        "bot_buy": True
    },
    "BCH":{
        "min_swap": 0.01,
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.bitcoin.com/bch/tx",
        "electrum": [{"url":"electron.coinucopia.io:50001"},
                     {"url":"bch.imaginary.cash:50001"},
                     {"url":"wallet.satoshiscoffeehouse.com:50001"},
                     {"url":"electroncash.dk:50001"},
                     {"url":"electron-cash.dragon.zone:50001"}],
        "reserve_balance":1,
        "premium":1.03,
        "min_swap":0.01,
        "minQty":"0.00001000",
        "maxQty":"900000.00000000",
        "stepSize":"0.00001000",
        "bot_sell": True,
        "bot_buy": True
    },
    "BET":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://bet.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10012"},
                     {"url":"electrum2.cipig.net:10012"},
                     {"url":"electrum3.cipig.net:10012"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "BOTS":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://bots.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10007"},
                     {"url":"electrum2.cipig.net:10007"},
                     {"url":"electrum3.cipig.net:10007"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "BTC":{
        "api-id": "bitcoin",
        "activate_with":"electrum",
        "reserve_balance":0.02,
        "tx_explorer":"https://explorer.bitcoin.com/btc/tx",
        "electrum": [{"url":"electrum1.cipig.net:10000"},
                     {"url":"electrum2.cipig.net:10000"},
                     {"url":"electrum3.cipig.net:10000"}],
        "bot_sell": False,
        "bot_buy": True
    },
    "BTCH":{
        "min_swap": 0.1,
        "api-id": "bitcoin-hush",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://bots.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10020"},
                     {"url":"electrum2.cipig.net:10020"},
                     {"url":"electrum3.cipig.net:10020"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "BUSD":{
        "min_swap": 0.5,
        "activate_with":"electrum",
        "api-id": "",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": True,
        "bot_buy": True
    },
    "DAI":{
        "min_swap": 0.5,
        "activate_with":"electrum",
        "api-id": "",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": True,
        "bot_buy": True
    },
    "CHIPS":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://chips.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10053"},
                     {"url":"electrum2.cipig.net:10053"},
                     {"url":"electrum3.cipig.net:10053"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "CCL":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://commod.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10029"},
                     {"url":"electrum2.cipig.net:10029"},
                     {"url":"electrum3.cipig.net:10029"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "COQUI":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://coqui.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10011"},
                     {"url":"electrum2.cipig.net:10011"},
                     {"url":"electrum3.cipig.net:10011"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "CRYPTO":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://crypto.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10008"},
                     {"url":"electrum2.cipig.net:10008"},
                     {"url":"electrum3.cipig.net:10008"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "DAI":{
        "min_swap": 0.5,
        "api-id": "dai",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "DASH":{
        "api-id": "dash",
        "min_swap": 0.01,
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.dash.org/tx",
        "electrum":  [{"url":"electrum1.cipig.net:10061"},
                      {"url":"electrum2.cipig.net:10061"},
                      {"url":"electrum3.cipig.net:10061"}],
        "reserve_balance":0.5,
        "premium":1.03,
        "min_swap":0.01,
        "minQty":"0.00100000",
        "maxQty":"900000.00000000",
        "stepSize":"0.00100000",
        "bot_sell": True,
        "bot_buy": True
    },
    "DEX":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "override_KMD_buy_price":10,
        "tx_explorer":"https://dex.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10006"},
                     {"url":"electrum2.cipig.net:10006"},
                     {"url":"electrum3.cipig.net:10006"}],
        "bot_sell": False,
        "bot_buy": True
    },
    "DGB":{
        "api-id": "digibyte",
        "min_swap": 10,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://digiexplorer.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10059"},
                     {"url":"electrum2.cipig.net:10059"},
                     {"url":"electrum3.cipig.net:10059"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "DOGE":{
        "api-id": "dogecoin",
        "activate_with":"electrum",
        "tx_explorer":"https://live.blockcypher.com/doge/tx",
        "min_swap": 10,
        "electrum": [{"url":"electrum1.cipig.net:10060"},
                     {"url":"electrum2.cipig.net:10060"},
                     {"url":"electrum3.cipig.net:10060"}],
        "reserve_balance":10000,
        "premium":1.0377,
        "min_swap":10,
        "minQty":"1.00000000",
        "maxQty":"90000000.00000000",
        "stepSize":"1.00000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "ECA":{
        "min_swap": 1,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://explorer.electraproject.org/tx",
        "electrum": [{"url":"electrum1.cipig.net:10052"},
                     {"url":"electrum2.cipig.net:10052"},
                     {"url":"electrum3.cipig.net:10052"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "EMC2":{
        "min_swap": 1,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"",
        "electrum": [{"url":"electrum1.cipig.net:10062"},
                     {"url":"electrum2.cipig.net:10062"},
                     {"url":"electrum3.cipig.net:10062"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "ETH":{
        "api-id": "ethereum",
        "activate_with":"electrum",
        "min_swap": 0.01,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "reserve_balance":1,
        "premium":1.03,
        "min_swap":0.01,
        "minQty":"0.001000000",
        "maxQty":"100000.00000000",
        "stepSize":"0.001000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "FIRO":{
        "min_swap": 1,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"",
        "electrum": [{"url":"electrumx.zcoin.io:50001"},
                     {"url":"electrumx01.zcoin.io:50001"},
                     {"url":"electrumx02.zcoin.io:50001"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "FTC":{
        "min_swap": 1,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://fsight.chain.tips/tx",
        "electrum": [{"url":"electrum1.cipig.net:10054"},
                     {"url":"electrum2.cipig.net:10054"},
                     {"url":"electrum3.cipig.net:10054"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "GLEEC":{
        "min_swap": 1,
        "api-id": "hush",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"",
        "electrum": [{"url":"electrum1.cipig.net:10069"},
                     {"url":"electrum2.cipig.net:10069"},
                     {"url":"electrum3.cipig.net:10069"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "HODL":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "override_KMD_buy_price":10,
        "tx_explorer":"https://hodl.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10009"},
                     {"url":"electrum2.cipig.net:10009"},
                     {"url":"electrum3.cipig.net:10009"}],
        "bot_sell": False,
        "bot_buy": True
    },
    "ILN":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "override_KMD_buy_price":10,
        "tx_explorer":"https://iln.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.ilien.io:65011"},
                     {"url":"electrum2.ilien.io:65011"}],
        "bot_sell": False,
        "bot_buy": True
    },
    "JUMBLR":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "override_KMD_buy_price":10,
        "tx_explorer":"https://jumblr.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10004"},
                     {"url":"electrum2.cipig.net:10004"},
                     {"url":"electrum3.cipig.net:10004"}],
        "bot_sell": False,
        "bot_buy": True
    },
    "KMD":{
        "api-id": "komodo",
        "activate_with":"electrum",
        "tx_explorer":"https://www.kmdexplorer.io/tx",
        "electrum": [{"url":"electrum1.cipig.net:10001"},
                     {"url":"electrum2.cipig.net:10001"},
                     {"url":"electrum3.cipig.net:10001"}],
        "reserve_balance":100,
        "premium":1.03,
        "min_swap":0.1,
        "minQty":"0.01000000",
        "maxQty":"90000000.00000000",
        "stepSize":"0.01000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "KOIN":{
        "api-id": "",
        "activate_with":"electrum",
        "tx_explorer":"https://koin.kmdexplorer.io/tx",
        "electrum": [{"url":"electrum1.cipig.net:10024"},
                     {"url":"electrum2.cipig.net:10024"},
                     {"url":"electrum3.cipig.net:10024"}],
        "reserve_balance":1,
        "min_swap":0.1,
        "bot_sell": True,
        "bot_buy": True
    },
    "KMDICE":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://kmdice.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10031"},
                     {"url":"electrum2.cipig.net:10031"},
                     {"url":"electrum3.cipig.net:10031"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "LABS":{
        "min_swap": 5,
        "use_api":"graviex",
        "activate_with":"electrum",
        "reserve_balance":50000,
        "override_KMD_buy_price":0.015,
        "override_KMD_sell_price":0.03,
        "premium":1.05,
        "tx_explorer":"https://labs.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10019"},
                     {"url":"electrum2.cipig.net:10019"},
                     {"url":"electrum3.cipig.net:10019"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "LINK":{
        "min_swap": 0.5,
        "activate_with":"electrum",
        "api-id": "chainlink",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "reserve_balance":20,
        "premium":1.03,
        "minQty":"1.00000000",
        "maxQty":"90000000.00000000",
        "stepSize":"1.00000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "LTC":{
        "api-id": "litecoin",
        "min_swap": 0.01,
        "activate_with":"electrum",
        "tx_explorer":"https://live.blockcypher.com/ltc/tx",
        "electrum": [{"url":"electrum-ltc.bysh.me:50001"},
                     {"url":"electrum.ltc.xurious.com:50001"},
                     {"url":"ltc.rentonisk.com:50001"},
                     {"url":"backup.electrum-ltc.org:50001"}],
        "reserve_balance":1,
        "premium":1.03,
        "min_swap":0.01,
        "minQty":"0.01000000",
        "maxQty":"100000.00000000",
        "stepSize":"0.01000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "MORTY":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://morty.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10018"},
                     {"url":"electrum2.cipig.net:10018"},
                     {"url":"electrum3.cipig.net:10018"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "MCL":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://mcl.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10023"},
                     {"url":"electrum2.cipig.net:10023"},
                     {"url":"electrum3.cipig.net:10023"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "MGW":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://mgw.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10015"},
                     {"url":"electrum2.cipig.net:10015"},
                     {"url":"electrum3.cipig.net:10015"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "MSHARK":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://mshark.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10013"},
                     {"url":"electrum2.cipig.net:10013"},
                     {"url":"electrum3.cipig.net:10013"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "MONA":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"",
        "electrum": [{"url":"electrumx3.monacoin.nl:50001"},
                     {"url":"electrumx1.monacoin.ninja:50001"},
                     {"url":"electrumx.tamami-foundation.org:50001"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "NAV":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"",
        "electrum": [{"url":"electrum1.cipig.net:10056"},
                     {"url":"electrum2.cipig.net:10056"},
                     {"url":"electrum3.cipig.net:10056"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "NMC":{
        "min_swap": 0.1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"",
        "electrum": [{"url":"electrumx1.nmc.bitclc.net:50001"},
                     {"url":"electrumx2.nmc.bitclc.net:50001"},
                     {"url":"electrumx3.nmc.bitclc.net:50001"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "OOT":{
        "min_swap": 1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://oot.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.utrum.io:10088"},
                     {"url":"electrum2.utrum.io:10088"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "PAX":{
        "min_swap": 0.5,
        "api-id": "paxos-standard",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "RFOX":{
        "min_swap": 0.5,
        "api-id": "paxos-standard",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "PBC":{
        "min_swap": 1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://oot.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10070"},
                     {"url":"electrum2.cipig.net:10070"},
                     {"url":"electrum3.cipig.net:10070"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "PANGEA":{
        "min_swap": 1,
        "api-id": "",
        "reserve_balance":2,
        "activate_with":"electrum",
        "tx_explorer":"https://pangea.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10010"},
                     {"url":"electrum2.cipig.net:10010"},
                     {"url":"electrum3.cipig.net:10010"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "QTUM":{
        "min_swap": 4,
        "activate_with":"electrum",
        "tx_explorer":"https://qtum.info/tx",
        "electrum": [{"url":"s1.qtum.info:50001"},
                     {"url":"s2.qtum.info:50001"},
                     {"url":"s3.qtum.info:50001"},
                     {"url":"s4.qtum.info:50001"},
                     {"url":"s5.qtum.info:50001"},
                     {"url":"s6.qtum.info:50001"},
                     {"url":"s7.qtum.info:50001"},
                     {"url":"s8.qtum.info:50001"},
                     {"url":"s9.qtum.info:50001"}
                     ],
        "reserve_balance":50,
        "premium":1.03,
        "min_swap":3.4,
        "minQty":"0.01000000",
        "maxQty":"10000000.00000000",
        "stepSize":"0.01000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "REVS":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://revs.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10003"},
                     {"url":"electrum2.cipig.net:10003"},
                     {"url":"electrum3.cipig.net:10003"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "RVN":{
        "min_swap": 5,
        "activate_with":"electrum",
        "tx_explorer":"https://ravencoin.network/tx",
        "electrum": [{"url":"electrum1.cipig.net:10051"},
                     {"url":"electrum2.cipig.net:10051"},
                     {"url":"electrum3.cipig.net:10051"}],
        "reserve_balance":2500,
        "premium":1.03,
        "min_swap":1,
        "minQty":"1.00000000",
        "maxQty":"90000000.00000000",
        "stepSize":"1.00000000",
        "bot_sell": True,
        "bot_buy": True
    },
    "SPACE":{
        "min_swap": 5,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://space.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.spaceworks.co:50001"},
                     {"url":"electrum2.spaceworks.co:50001"},
                     {"url":"electrum1.spaceworks.co:50002"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "RICK":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://rick.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10017"},
                     {"url":"electrum2.cipig.net:10017"},
                     {"url":"electrum3.cipig.net:10017"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "SUPERNET":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://supernet.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10005"},
                     {"url":"electrum2.cipig.net:10005"},
                     {"url":"electrum3.cipig.net:10005"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "THC":{
        "min_swap": 5,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://thc.explorer.dexstats.info/tx",
        "electrum": [{"url":"165.22.52.123:10022"},
                     {"url":"157.230.45.184:10022"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "USDC":{
        "min_swap": 0.5,
        "api-id": "usd-coin",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "TUSD":{
        "min_swap": 0.5,
        "api-id": "true-usd",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "USDC":{
        "min_swap": 0.5,
        "api-id": "true-usd",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "VRA":{
        "min_swap": 0.5,
        "api-id": "true-usd",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
        "bot_sell": False,
        "bot_buy": False
    },
    "VRSC":{        
        "min_swap": 0.1,
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://explorer.veruscoin.io/tx",
        "electrum": [{"url":"el0.veruscoin.io:17485"},
                     {"url":"el1.veruscoin.io:17485"},
                     {"url":"el2.veruscoin.io:17485"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "WLC":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://wlc.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10014"},
                     {"url":"electrum2.cipig.net:10014"},
                     {"url":"electrum3.cipig.net:10014"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "ZEC":{
        "min_swap": 0.1,
        "api-id": "zcash",
        "activate_with":"electrum",
        "reserve_balance":1,
        "tx_explorer":"https://explorer.zcha.in/transactions",
        "electrum": [{"url":"electrum3.cipig.net:10058"},
                     {"url":"electrum3.cipig.net:10058"},
                     {"url":"electrum3.cipig.net:10058"}],
        "bot_sell": True,
        "bot_buy": True
    },
    "ZER":{
        "min_swap": 0.1,
        "api-id": "zaddex",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"",
        "electrum": [{"url":"electrum1.cipig.net:10065"},
                     {"url":"electrum2.cipig.net:10065"},
                     {"url":"electrum3.cipig.net:10065"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "ZEXO":{
        "min_swap": 0.1,
        "api-id": "zaddex",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://zexo.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10035"},
                     {"url":"electrum2.cipig.net:10035"},
                     {"url":"electrum3.cipig.net:10035"}],
        "bot_sell": False,
        "bot_buy": False
    },
    "ZILLA":{
        "min_swap": 0.1,
        "api-id": "",
        "activate_with":"electrum",
        "reserve_balance":2,
        "tx_explorer":"https://zilla.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10028"},
                     {"url":"electrum2.cipig.net:10028"},
                     {"url":"electrum3.cipig.net:10028"}],
        "bot_sell": False,
        "bot_buy": False
    }
}

# Input coins you want to trade here. 
# reserve_balance: excess funds will be sent to your Binance wallet
# premium: value relative to binance market rate to setprices as marketmaker.
# min/max/stepsize need to be set from values from 
# https://api.binance.com/api/v1/exchangeInfo

cointags = []
buy_list = []
sell_list = []
for ticker in coins:
  cointags.append(ticker)
  if coins[ticker]['bot_buy']:
    buy_list.append(ticker)
  if coins[ticker]['bot_sell']:
    sell_list.append(ticker)
trading_list = list(set(buy_list+sell_list))
